### ISSUE TITLE
莫名的报错,有大佬知道嘛

### ISSUE THREAD

**Issue by Elivs728** [boy-hack/go-strip#13]
panic: no pclntab located

goroutine 1 [running]:
main.main()
        /home/runner/work/go-strip-source/go-strip-source/cmd/cmd.go:56 +0x218b

**Comment by jozxing** [comment]
> panic: no pclntab located
> 
> goroutine 1 [running]: main.main() /home/runner/work/go-strip-source/go-strip-source/cmd/cmd.go:56 +0x218b

同错误，解决了么？
