### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by websecer** [boy-hack/go-strip#9]
`panic: runtime error: slice bounds out of range [:6917919642050060544] with capacity 788480

goroutine 1 [running]:
gostrip/gore.parseString(0xc0000461c0, 0xff, 0x4ba000, {0xc0006fc000, 0xc0800, 0xc0800})
        /home/runner/work/go-strip-source/go-strip-source/gore/type.go:706 +0x1b4
gostrip/gore.typeParse(0x577e08?, 0xc0000461c0, 0x2c098, {0xc0006fc000, 0xc0800, 0xc0800}, 0x4ba000)
        /home/runner/work/go-strip-source/go-strip-source/gore/type.go:384 +0x34d
gostrip/gore.getLegacyTypes(0xc0000461c0, {0x578a78, 0xc00001e380})
        /home/runner/work/go-strip-source/go-strip-source/gore/type.go:117 +0x325
gostrip/gore.getTypes(0xc0000461c0, {0x578a78, 0xc00001e380})
        /home/runner/work/go-strip-source/go-strip-source/gore/type.go:61 +0x36e
gostrip/gore.(*GoFile).GetTypes(0xc000140000)
        /home/runner/work/go-strip-source/go-strip-source/gore/file.go:422 +0x71
main.main()
        /home/runner/work/go-strip-source/go-strip-source/cmd/cmd.go:72 +0x312`

**Comment by veo** [comment]
panic: runtime error: slice bounds out of range [:3612844831] with capacity 335360
一样的问题

**Comment by kakuilan** [comment]
一样
`
2022/09/16 17:30:58 GoRoot获取失败，err: no goroot found
panic: runtime error: slice bounds out of range [:14652563515960607797] with capacity 3344896

goroutine 1 [running]:
gostrip/gore.parseString(0xc00007c180, 0xc4834818246c8b48, 0x1000, {0xc0023a0000, 0x330a00, 0x330a00})
	/home/runner/work/go-strip-source/go-strip-source/gore/type.go:706 +0x1b4
gostrip/gore.typeParse(0x56ace8?, 0xc00007c180, 0x2440b, {0xc0023a0000, 0x330a00, 0x330a00}, 0x1000)
	/home/runner/work/go-strip-source/go-strip-source/gore/type.go:384 +0x34d
gostrip/gore.getLegacyTypes(0xc00007c180, {0x56b998, 0xc000024080})
	/home/runner/work/go-strip-source/go-strip-source/gore/type.go:117 +0x325
gostrip/gore.getTypes(0xc00007c180, {0x56b998, 0xc000024080})
	/home/runner/work/go-strip-source/go-strip-source/gore/type.go:61 +0x36e
gostrip/gore.(*GoFile).GetTypes(0xc000156000)
	/home/runner/work/go-strip-source/go-strip-source/gore/file.go:422 +0x71
main.main()
	/home/runner/work/go-strip-source/go-strip-source/cmd/cmd.go:72 +0x312

`

**Comment by NotAzay** [comment]
一样的问题，go 1.18.6  二进制文件大小45Mb，go build -ldflags "-s -w -H=windowsgui" -buildmode=pie
